name: $(SourceBranchName) $(Rev:r)
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  - group: azure

jobs:
  - job: build
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build Application
        inputs:
          command: publish
          arguments: '--configuration Release --output publish_output'
          projects: '*.csproj'
          publishWebProjects: false
          modifyOutputPath: false
          zipAfterPublish: false

      - task: ArchiveFiles@2
        displayName: Archive Files
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
          includeRootFolder: false
          archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
          artifactName: 'drop'

      - task: AzureFunctionApp@1
        displayName: Azure Function App Deploy
        inputs:
          azureSubscription: $(azure.subscription)
          appType: functionApp
          appName: $(azure.appName)

  # - job: deploy
  #   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  #   steps:      
  #     - task: DotNetCoreCLI@2
  #       displayName: Build Application
  #       inputs:
  #         command: publish
  #         arguments: '--configuration Release --output publish_output'
  #         projects: '*.csproj'
  #         publishWebProjects: false
  #         modifyOutputPath: false
  #         zipAfterPublish: false

  #     - task: ArchiveFiles@2
  #       displayName: Archive Files
  #       inputs:
  #         rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
  #         includeRootFolder: false
  #         archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

  #     - task: PublishBuildArtifacts@1
  #       displayName: Publish Artifacts
  #       inputs:
  #         PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
  #         artifactName: 'drop'

